/**
 * httpbin.org MCP Server — GENERATED BY w2mcp from spec-less docs. Do not hand-edit.
 * Source: httpbin.org API docs.  Auth: none (confidence 1).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "https://httpbin.org";
// No authentication required (public API).

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {
  401: "Unsuccessful authentication.",
  412: "match",
  404: "Unsuccessful authentication.",
  400: "Client Errors",
  500: "Server Errors",
};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`httpbin.org ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "httpbin-org", version: "0.1.0" });

server.tool(
  "get_absolute_redirect_n",
  "Absolutely 302 Redirects n times.",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/absolute-redirect/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_anything",
  "Returns anything passed in request data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/anything";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "patch_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_anything_anything",
  "Returns anything passed in request data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/anything/{anything}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_anything_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything/{anything}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_anything_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything/{anything}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "patch_anything_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything/{anything}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_anything_anything",
  "[UNVERIFIED WRITE] Returns anything passed in request data.",
  {
  
    },
  async (args: any) => {
    let path = "/anything/{anything}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_base64_value",
  "Decodes base64url-encoded string.",
  {
      "value": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/base64/{value}";
    for (const k of ["value"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["value","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_basic_auth_user_passwd",
  "Prompts the user for authorization using HTTP Basic Auth.",
  {
      "user": z.string(),
      "passwd": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/basic-auth/{user}/{passwd}";
    for (const k of ["user","passwd"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["user","passwd","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_bearer",
  "Prompts the user for authorization using bearer authentication.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/bearer";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_brotli",
  "Returns Brotli-encoded data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/brotli";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_bytes_n",
  "Returns n random bytes generated with given seed",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/bytes/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cache",
  "Returns a 304 if an If-Modified-Since header or If-None-Match is present. Returns the same as a GET otherwise.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cache";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cache_value",
  "Sets a Cache-Control header for n seconds.",
  {
      "value": z.number(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cache/{value}";
    for (const k of ["value"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["value","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cookies",
  "Returns cookie data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cookies";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cookies_delete",
  "Deletes cookie(s) as provided by the query string and redirects to cookie list.",
  {
      "freeform": z.record(z.any()).optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cookies/delete";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["freeform"]);
    const body = omit(args, ["freeform","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cookies_set",
  "Sets cookie(s) as provided by the query string and redirects to cookie list.",
  {
      "freeform": z.record(z.any()).optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cookies/set";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["freeform"]);
    const body = omit(args, ["freeform","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_cookies_set_name_value",
  "Sets a cookie and redirects to cookie list.",
  {
      "name": z.string(),
      "value": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/cookies/set/{name}/{value}";
    for (const k of ["name","value"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["name","value","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_deflate",
  "Returns Deflate-encoded data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/deflate";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_delay_delay",
  "Returns a delayed response (max of 10 seconds).",
  {
      "delay": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/delay/{delay}";
    for (const k of ["delay"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["delay","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_delay_delay",
  "[UNVERIFIED WRITE] Returns a delayed response (max of 10 seconds).",
  {
      "delay": z.string(),
    },
  async (args: any) => {
    let path = "/delay/{delay}";
    for (const k of ["delay"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["delay","verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_delay_delay",
  "[UNVERIFIED WRITE] Returns a delayed response (max of 10 seconds).",
  {
      "delay": z.string(),
    },
  async (args: any) => {
    let path = "/delay/{delay}";
    for (const k of ["delay"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["delay","verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "patch_delay_delay",
  "[UNVERIFIED WRITE] Returns a delayed response (max of 10 seconds).",
  {
      "delay": z.string(),
    },
  async (args: any) => {
    let path = "/delay/{delay}";
    for (const k of ["delay"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["delay","verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_delay_delay",
  "[UNVERIFIED WRITE] Returns a delayed response (max of 10 seconds).",
  {
      "delay": z.string(),
    },
  async (args: any) => {
    let path = "/delay/{delay}";
    for (const k of ["delay"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["delay","verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_delete",
  "[UNVERIFIED WRITE] The request's DELETE parameters.",
  {
  
    },
  async (args: any) => {
    let path = "/delete";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_deny",
  "Returns page denied by robots.txt rules.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/deny";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_digest_auth_qop_user_passwd",
  "Prompts the user for authorization using Digest Auth.",
  {
      "qop": z.string().describe("auth or auth-int"),
      "user": z.string(),
      "passwd": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/digest-auth/{qop}/{user}/{passwd}";
    for (const k of ["qop","user","passwd"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["qop","user","passwd","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_digest_auth_qop_user_passwd_algorithm",
  "Prompts the user for authorization using Digest Auth + Algorithm.",
  {
      "qop": z.string().describe("auth or auth-int"),
      "user": z.string(),
      "passwd": z.string(),
      "algorithm": z.string().describe("MD5, SHA-256, SHA-512"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}";
    for (const k of ["qop","user","passwd","algorithm"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["qop","user","passwd","algorithm","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_digest_auth_qop_user_passwd_algorithm_stale_after",
  "Prompts the user for authorization using Digest Auth + Algorithm.",
  {
      "qop": z.string().describe("auth or auth-int"),
      "user": z.string(),
      "passwd": z.string(),
      "algorithm": z.string().describe("MD5, SHA-256, SHA-512"),
      "stale_after": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}/{stale_after}";
    for (const k of ["qop","user","passwd","algorithm","stale_after"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["qop","user","passwd","algorithm","stale_after","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_drip",
  "Drips data over a duration after an optional initial delay.",
  {
      "duration": z.number().describe("The amount of time (in seconds) over which to drip each byte").optional(),
      "numbytes": z.number().describe("The number of bytes to respond with").optional(),
      "code": z.number().describe("The response code that will be returned").optional(),
      "delay": z.number().describe("The amount of time (in seconds) to delay before responding").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/drip";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["duration","numbytes","code","delay"]);
    const body = omit(args, ["duration","numbytes","code","delay","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_encoding_utf8",
  "Returns a UTF-8 encoded body.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/encoding/utf8";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_etag_etag",
  "Assumes the resource has the given etag and responds to If-None-Match and If-Match headers appropriately.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/etag/{etag}";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_get",
  "The request's query parameters.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/get";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_gzip",
  "Returns GZip-encoded data.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/gzip";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_headers",
  "Return the incoming request's HTTP headers.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/headers";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_hidden_basic_auth_user_passwd",
  "Prompts the user for authorization using HTTP Basic Auth.",
  {
      "user": z.string(),
      "passwd": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/hidden-basic-auth/{user}/{passwd}";
    for (const k of ["user","passwd"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["user","passwd","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_html",
  "Returns a simple HTML document.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/html";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_image",
  "Returns a simple image of the type suggest by the Accept header.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/image";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_image_jpeg",
  "Returns a simple JPEG image.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/image/jpeg";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_image_png",
  "Returns a simple PNG image.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/image/png";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_image_svg",
  "Returns a simple SVG image.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/image/svg";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_image_webp",
  "Returns a simple WEBP image.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/image/webp";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_ip",
  "Returns the requester's IP Address.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/ip";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_json",
  "Returns a simple JSON document.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/json";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_links_n_offset",
  "Generate a page containing n links to other pages which do the same.",
  {
      "n": z.string(),
      "offset": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/links/{n}/{offset}";
    for (const k of ["n","offset"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","offset","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "patch_patch",
  "[UNVERIFIED WRITE] The request's PATCH parameters.",
  {
  
    },
  async (args: any) => {
    let path = "/patch";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "post_post",
  "[UNVERIFIED WRITE] The request's POST parameters.",
  {
  
    },
  async (args: any) => {
    let path = "/post";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_put",
  "[UNVERIFIED WRITE] The request's PUT parameters.",
  {
  
    },
  async (args: any) => {
    let path = "/put";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_range_numbytes",
  "Streams n random bytes generated with given seed, at given chunk size per packet.",
  {
      "numbytes": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/range/{numbytes}";
    for (const k of ["numbytes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["numbytes","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_redirect_to",
  "302/3XX Redirects to the given URL.",
  {
      "url": z.string(),
      "status_code": z.string().optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/redirect-to";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["url","status_code"]);
    const body = omit(args, ["url","status_code","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_redirect_to",
  "[UNVERIFIED WRITE] 302/3XX Redirects to the given URL.",
  {
  
    },
  async (args: any) => {
    let path = "/redirect-to";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_redirect_to",
  "[UNVERIFIED WRITE] 302/3XX Redirects to the given URL.",
  {
  
    },
  async (args: any) => {
    let path = "/redirect-to";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "patch_redirect_to",
  "[UNVERIFIED WRITE] 302/3XX Redirects to the given URL.",
  {
  
    },
  async (args: any) => {
    let path = "/redirect-to";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_redirect_to",
  "[UNVERIFIED WRITE] 302/3XX Redirects to the given URL.",
  {
  
    },
  async (args: any) => {
    let path = "/redirect-to";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_redirect_n",
  "302 Redirects n times.",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/redirect/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_relative_redirect_n",
  "Relatively 302 Redirects n times.",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/relative-redirect/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_response_headers",
  "Returns a set of response headers from the query string.",
  {
      "freeform": z.record(z.any()).optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/response-headers";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["freeform"]);
    const body = omit(args, ["freeform","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_response_headers",
  "[UNVERIFIED WRITE] Returns a set of response headers from the query string.",
  {
      "freeform": z.record(z.any()).optional(),
    },
  async (args: any) => {
    let path = "/response-headers";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["freeform"]);
    const body = omit(args, ["freeform","verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_robots_txt",
  "Returns some robots.txt rules.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/robots.txt";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_status_codes",
  "Return status code or random status code if more than one are given",
  {
      "codes": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/status/{codes}";
    for (const k of ["codes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["codes","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "post_status_codes",
  "[UNVERIFIED WRITE] Return status code or random status code if more than one are given",
  {
      "codes": z.string(),
    },
  async (args: any) => {
    let path = "/status/{codes}";
    for (const k of ["codes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["codes","verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "put_status_codes",
  "[UNVERIFIED WRITE] Return status code or random status code if more than one are given",
  {
      "codes": z.string(),
    },
  async (args: any) => {
    let path = "/status/{codes}";
    for (const k of ["codes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["codes","verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "patch_status_codes",
  "[UNVERIFIED WRITE] Return status code or random status code if more than one are given",
  {
      "codes": z.string(),
    },
  async (args: any) => {
    let path = "/status/{codes}";
    for (const k of ["codes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["codes","verbosity"]);
    const raw = await call("PATCH", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_status_codes",
  "[UNVERIFIED WRITE] Return status code or random status code if more than one are given",
  {
      "codes": z.string(),
    },
  async (args: any) => {
    let path = "/status/{codes}";
    for (const k of ["codes"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["codes","verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_stream_bytes_n",
  "Streams n random bytes generated with given seed, at given chunk size per packet.",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/stream-bytes/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_stream_n",
  "Stream n JSON responses",
  {
      "n": z.string(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/stream/{n}";
    for (const k of ["n"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["n","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_user_agent",
  "Return the incoming requests's User-Agent header.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/user-agent";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_uuid",
  "Return a UUID4.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/uuid";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_xml",
  "Returns a simple XML document.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/xml";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      await handle();
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`httpbin-org MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (W2MCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.W2MCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
