/**
 * SpaceX API MCP Server — GENERATED BY w2mcp from spec-less docs. Do not hand-edit.
 * Source: SpaceX API API docs.  Auth: unknown (confidence 0).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { AsyncLocalStorage } from "node:async_hooks";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "https://api.spacexdata.com/v4/";
export const credentialContext = new AsyncLocalStorage<string>();
function resolveToken(): string {
  const t = credentialContext.getStore() ?? process.env.SPACEX_API_TOKEN;
  if (!t) throw new Error("No credential for SpaceX API: set SPACEX_API_TOKEN or inject via the gateway.");
  return t;
}

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {

};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Authorization": "Bearer {token}".replace("{token}", resolveToken()),
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`SpaceX API ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "spacex-api", version: "0.1.0" });



  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      const cred = req.headers["x-w2mcp-credential"]; await (cred ? credentialContext.run(String(cred), handle) : handle()); // per-request credential injected by the gateway
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`spacex-api MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (W2MCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.W2MCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
