/**
 * Swagger Petstore - OpenAPI 3.0 MCP Server — GENERATED BY anymcp from spec-less docs. Do not hand-edit.
 * Source: Swagger Petstore - OpenAPI 3.0 API docs.  Auth: oauth2 (confidence 1).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { AsyncLocalStorage } from "node:async_hooks";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "/api/v3";
export const credentialContext = new AsyncLocalStorage<string>();
function resolveToken(): string {
  const t = credentialContext.getStore() ?? process.env.SWAGGER_PETSTORE_OPENAPI_3_0_TOKEN;
  if (!t) throw new Error("No credential for Swagger Petstore - OpenAPI 3.0: set SWAGGER_PETSTORE_OPENAPI_3_0_TOKEN or inject via the gateway.");
  return t;
}

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {
  400: "Invalid input",
  422: "Validation exception",
  404: "Pet not found",
};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Authorization": "Bearer {token}".replace("{token}", resolveToken()),
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Swagger Petstore - OpenAPI 3.0 ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "swagger-petstore-openapi-3-0", version: "0.1.0" });

server.tool(
  "add_pet",
  "[UNVERIFIED WRITE] Add a new pet to the store.",
  {
      "id": z.number().describe("Example: 10").optional(),
      "name": z.string().describe("Example: \"doggie\""),
      "category": z.record(z.any()).optional(),
      "photoUrls": z.array(z.string()),
      "tags": z.array(z.record(z.any())).optional(),
      "status": z.enum(["available","pending","sold"] as [string, ...string[]]).describe("pet status in the store").optional(),
    },
  async (args: any) => {
    let path = "/pet";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "update_pet",
  "[UNVERIFIED WRITE] Update an existing pet.",
  {
      "id": z.number().describe("Example: 10").optional(),
      "name": z.string().describe("Example: \"doggie\""),
      "category": z.record(z.any()).optional(),
      "photoUrls": z.array(z.string()),
      "tags": z.array(z.record(z.any())).optional(),
      "status": z.enum(["available","pending","sold"] as [string, ...string[]]).describe("pet status in the store").optional(),
    },
  async (args: any) => {
    let path = "/pet";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "find_pets_by_status",
  "Finds Pets by status.",
  {
      "status": z.enum(["available","pending","sold"] as [string, ...string[]]).describe("Status values that need to be considered for filter"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/pet/findByStatus";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["status"]);
    const body = omit(args, ["status","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "find_pets_by_tags",
  "Finds Pets by tags.",
  {
      "tags": z.array(z.string()).describe("Tags to filter by"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/pet/findByTags";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["tags"]);
    const body = omit(args, ["tags","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_pet_by_id",
  "Find pet by ID.",
  {
      "petId": z.number().describe("ID of pet to return"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/pet/{petId}";
    for (const k of ["petId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["petId","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "update_pet_with_form",
  "[UNVERIFIED WRITE] Updates a pet in the store with form data.",
  {
      "petId": z.number().describe("ID of pet that needs to be updated"),
      "name": z.string().describe("Name of pet that needs to be updated").optional(),
      "status": z.string().describe("Status of pet that needs to be updated").optional(),
    },
  async (args: any) => {
    let path = "/pet/{petId}";
    for (const k of ["petId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["name","status"]);
    const body = omit(args, ["petId","name","status","verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_pet",
  "[UNVERIFIED WRITE] Deletes a pet.",
  {
      "petId": z.number().describe("Pet id to delete"),
    },
  async (args: any) => {
    let path = "/pet/{petId}";
    for (const k of ["petId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["petId","verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "upload_file",
  "[UNVERIFIED WRITE] Uploads an image.",
  {
      "petId": z.number().describe("ID of pet to update"),
      "additionalMetadata": z.string().describe("Additional Metadata").optional(),
    },
  async (args: any) => {
    let path = "/pet/{petId}/uploadImage";
    for (const k of ["petId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["additionalMetadata"]);
    const body = omit(args, ["petId","additionalMetadata","verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_inventory",
  "Returns pet inventories by status.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/store/inventory";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "place_order",
  "[UNVERIFIED WRITE] Place an order for a pet.",
  {
      "id": z.number().describe("Example: 10").optional(),
      "petId": z.number().describe("Example: 198772").optional(),
      "quantity": z.number().describe("Example: 7").optional(),
      "shipDate": z.string().optional(),
      "status": z.enum(["placed","approved","delivered"] as [string, ...string[]]).describe("Order Status Example: \"approved\"").optional(),
      "complete": z.boolean().optional(),
    },
  async (args: any) => {
    let path = "/store/order";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "get_order_by_id",
  "Find purchase order by ID.",
  {
      "orderId": z.number().describe("ID of order that needs to be fetched"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/store/order/{orderId}";
    for (const k of ["orderId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["orderId","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "delete_order",
  "[UNVERIFIED WRITE] Delete purchase order by identifier.",
  {
      "orderId": z.number().describe("ID of the order that needs to be deleted"),
    },
  async (args: any) => {
    let path = "/store/order/{orderId}";
    for (const k of ["orderId"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["orderId","verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "create_user",
  "[UNVERIFIED WRITE] Create user.",
  {
      "id": z.number().describe("Example: 10").optional(),
      "username": z.string().describe("Example: \"theUser\"").optional(),
      "firstName": z.string().describe("Example: \"John\"").optional(),
      "lastName": z.string().describe("Example: \"James\"").optional(),
      "email": z.string().describe("Example: \"john@email.com\"").optional(),
      "password": z.string().describe("Example: \"12345\"").optional(),
      "phone": z.string().describe("Example: \"12345\"").optional(),
      "userStatus": z.number().describe("User Status Example: 1").optional(),
    },
  async (args: any) => {
    let path = "/user";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "create_users_with_list_input",
  "[UNVERIFIED WRITE] Creates list of users with given input array.",
  {
      "body": z.array(z.record(z.any())).describe("Request body.").optional(),
    },
  async (args: any) => {
    let path = "/user/createWithList";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("POST", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "login_user",
  "Logs user into the system.",
  {
      "username": z.string().describe("The user name for login").optional(),
      "password": z.string().describe("The password for login in clear text").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/user/login";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["username","password"]);
    const body = omit(args, ["username","password","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "logout_user",
  "Logs out current logged in user session.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/user/logout";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_user_by_name",
  "Get user by user name.",
  {
      "username": z.string().describe("The name that needs to be fetched. Use user1 for testing"),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/user/{username}";
    for (const k of ["username"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["username","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "update_user",
  "[UNVERIFIED WRITE] Update user resource.",
  {
      "username": z.string().describe("name that need to be deleted"),
      "id": z.number().describe("Example: 10").optional(),
      "username": z.string().describe("Example: \"theUser\"").optional(),
      "firstName": z.string().describe("Example: \"John\"").optional(),
      "lastName": z.string().describe("Example: \"James\"").optional(),
      "email": z.string().describe("Example: \"john@email.com\"").optional(),
      "password": z.string().describe("Example: \"12345\"").optional(),
      "phone": z.string().describe("Example: \"12345\"").optional(),
      "userStatus": z.number().describe("User Status Example: 1").optional(),
    },
  async (args: any) => {
    let path = "/user/{username}";
    for (const k of ["username"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["username","verbosity"]);
    const raw = await call("PUT", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

server.tool(
  "delete_user",
  "[UNVERIFIED WRITE] Delete user resource.",
  {
      "username": z.string().describe("The name that needs to be deleted"),
    },
  async (args: any) => {
    let path = "/user/{username}";
    for (const k of ["username"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["username","verbosity"]);
    const raw = await call("DELETE", path + qs, Object.keys(body).length ? body : undefined);
    return { content: [{ type: "text", text: raw }] };
  }
);

  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      const cred = req.headers["x-anymcp-credential"]; await (cred ? credentialContext.run(String(cred), handle) : handle()); // per-request credential injected by the gateway
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`swagger-petstore-openapi-3-0 MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (ANYMCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.ANYMCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
