/**
 * Frankfurter MCP Server — GENERATED BY anymcp from spec-less docs. Do not hand-edit.
 * Source: Frankfurter API docs.  Auth: none (confidence 1).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "https://api.frankfurter.dev";
// No authentication required (public API).

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {
  400: "Invalid parameter or malformed request.",
  404: "Currency, rate, or resource not found.",
  422: "Request understood but cannot be processed.",
};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Frankfurter ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "frankfurter", version: "0.1.0" });

server.tool(
  "get_rates",
  "Fetch the latest exchange rates.",
  {
      "base": z.string().describe("Change the base currency (e.g., USD).").optional(),
      "quotes": z.array(z.string()).describe("Filter target currencies, provided as a comma-separated list of currency codes (e.g., USD,GBP).").optional(),
      "date": z.string().describe("Look up rates for a specific date (YYYY-MM-DD).").optional(),
      "from": z.string().describe("Fetch rates over a period, starting from this date (YYYY-MM-DD).").optional(),
      "to": z.string().describe("Fetch rates over a period, ending on this date (YYYY-MM-DD).").optional(),
      "group": z.enum(["week","month"] as [string, ...string[]]).describe("Downsample a time series. Supports 'week' and 'month'.").optional(),
      "providers": z.array(z.string()).describe("Scope to specific providers, provided as a comma-separated list of provider keys (e.g., ECB).").optional(),
      "expand": z.enum(["providers"] as [string, ...string[]]).describe("Add 'expand=providers' to see which providers contributed to each blended rate.").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/rates";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["base","quotes","date","from","to","group","providers","expand"]);
    const body = omit(args, ["base","quotes","date","from","to","group","providers","expand","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_rate",
  "Get the rate for a single currency pair.",
  {
      "base_currency": z.string().describe("The base currency code (e.g., EUR)."),
      "quote_currency": z.string().describe("The quote currency code (e.g., USD)."),
      "date": z.string().describe("Look up the rate for a specific date (YYYY-MM-DD).").optional(),
      "providers": z.array(z.string()).describe("Scope to specific providers, provided as a comma-separated list of provider keys (e.g., ECB).").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/rate/{base_currency}/{quote_currency}";
    for (const k of ["base_currency","quote_currency"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["date","providers"]);
    const body = omit(args, ["base_currency","quote_currency","date","providers","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_currencies",
  "Get available currencies with provider coverage.",
  {
      "scope": z.enum(["all"] as [string, ...string[]]).describe("Include legacy currencies. Set to 'all' to include them.").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/currencies";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["scope"]);
    const body = omit(args, ["scope","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "get_currency_details",
  "Get details and provider coverage for a single currency.",
  {
      "currency_code": z.string().describe("The currency code (e.g., EUR)."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/currency/{currency_code}";
    for (const k of ["currency_code"]) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["currency_code","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_providers",
  "List the data sources behind the API.",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/providers";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      await handle();
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`frankfurter MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (ANYMCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.ANYMCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
