/**
 * Free Recipe API MCP Server — GENERATED BY w2mcp from spec-less docs. Do not hand-edit.
 * Source: Free Recipe API API docs.  Auth: api_key (confidence 0.9).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { AsyncLocalStorage } from "node:async_hooks";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "https://www.themealdb.com/api/json/";
export const credentialContext = new AsyncLocalStorage<string>();
function resolveToken(): string {
  const t = credentialContext.getStore() ?? process.env.FREE_RECIPE_API_TOKEN;
  if (!t) throw new Error("No credential for Free Recipe API: set FREE_RECIPE_API_TOKEN or inject via the gateway.");
  return t;
}

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {

};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Authorization": "The API key is a path segment (e.g., /v1/{api_key}/). The test key for the V1 API is '1'. Premium keys are also path segments in the V2 API.".replace("{token}", resolveToken()),
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Free Recipe API ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "free-recipe-api", version: "0.1.0" });

server.tool(
  "search_meal_by_name",
  "Search meal by name",
  {
      "s": z.string().describe("The name of the meal to search for."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/search.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["s"]);
    const body = omit(args, ["s","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_meals_by_first_letter",
  "List all meals by first letter",
  {
      "f": z.string().describe("The first letter of the meal name."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/search.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["f"]);
    const body = omit(args, ["f","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "lookup_meal_details_by_id",
  "Lookup full meal details by id",
  {
      "i": z.string().describe("The ID of the meal to lookup."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/lookup.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["i"]);
    const body = omit(args, ["i","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "lookup_single_random_meal",
  "Lookup a single random meal",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/random.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "lookup_selection_of_random_meals",
  "Lookup a selection of 10 random meals",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/1/randomselection.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_all_meal_categories",
  "List all meal categories",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/categories.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_latest_meals",
  "Latest Meals",
  {
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/1/latest.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, []);
    const body = omit(args, ["verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_categories",
  "List all Categories",
  {
      "c": z.enum(["list"] as [string, ...string[]]).describe("Set to 'list' to retrieve all categories."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/list.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["c"]);
    const body = omit(args, ["c","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_areas",
  "List all Areas",
  {
      "a": z.enum(["list"] as [string, ...string[]]).describe("Set to 'list' to retrieve all areas."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/list.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["a"]);
    const body = omit(args, ["a","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "list_ingredients",
  "List all Ingredients",
  {
      "i": z.enum(["list"] as [string, ...string[]]).describe("Set to 'list' to retrieve all ingredients."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/list.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["i"]);
    const body = omit(args, ["i","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "filter_by_main_ingredient",
  "Filter by main ingredient",
  {
      "i": z.string().describe("The main ingredient name to filter by. Use underscores for spaces."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/filter.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["i"]);
    const body = omit(args, ["i","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "filter_by_multi_ingredient",
  "Filter by Multi-Ingredient",
  {
      "i": z.string().describe("A comma-separated list of ingredient names to filter by. Use underscores for spaces."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v2/1/filter.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["i"]);
    const body = omit(args, ["i","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "filter_by_category",
  "Filter by Category",
  {
      "c": z.string().describe("The category name to filter by."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/filter.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["c"]);
    const body = omit(args, ["c","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "filter_by_area",
  "Filter by Area",
  {
      "a": z.string().describe("The area name to filter by."),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/v1/1/filter.php";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["a"]);
    const body = omit(args, ["a","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      const cred = req.headers["x-w2mcp-credential"]; await (cred ? credentialContext.run(String(cred), handle) : handle()); // per-request credential injected by the gateway
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`free-recipe-api MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (W2MCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.W2MCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
