/**
 * CoinGecko API MCP Server — GENERATED BY anymcp from spec-less docs. Do not hand-edit.
 * Source: CoinGecko API API docs.  Auth: none (confidence 1).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { shapeResponse } from "./shape.js";

const BASE_URL = "https://api.coingecko.com/api/v3";
// No authentication required (public API).

// Per-API response noise fields (verbose metadata) stripped from tool output by the shaper.
// From the extractor's response_noise + a small curated registry. Conservative by design.
const NOISE_FIELDS: string[] = [];

const ERROR_MAP: Record<number, string> = {

};

async function call(method: string, path: string, body?: unknown): Promise<string> {
  const res = await fetch(BASE_URL + path, {
    method,
    headers: {
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`CoinGecko API ${res.status}: ${ERROR_MAP[res.status] ?? "error"} — ${text.slice(0, 300)}`);
  return text;
}

function buildQuery(args: any, keys: string[]): string {
  const parts: string[] = [];
  for (const k of keys) {
    const v = args[k];
    if (v === undefined || v === null) continue;
    for (const item of Array.isArray(v) ? v : [v]) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
  }
  return parts.length ? "?" + parts.join("&") : "";
}
function omit(args: any, keys: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!keys.includes(k) && v !== undefined) out[k] = v;
  return out;
}

export function createServer() {
  const server = new McpServer({ name: "coingecko-api", version: "0.1.0" });

server.tool(
  "coins_list_with_market_data",
  "To query all the supported coins with price, market cap, volume and market related data",
  {
      "vs_currency": z.string().describe("Target currency of coins and market data. *refers to /simple/supported_vs_currencies"),
      "ids": z.string().describe("Coins' IDs, comma-separated if querying more than 1 coin. *refers to /coins/list").optional(),
      "names": z.string().describe("Coins' names, comma-separated if querying more than 1 coin.").optional(),
      "symbols": z.string().describe("Coins' symbols, comma-separated if querying more than 1 coin.").optional(),
      "include_tokens": z.enum(["top","all"] as [string, ...string[]]).describe("For symbols lookups, specify all to include all matching tokens. Default top returns top-ranked tokens by market cap or volume.").optional(),
      "category": z.string().describe("Filter based on coins' category. *refers to /coins/categories/list").optional(),
      "order": z.enum(["market_cap_asc","market_cap_desc","volume_asc","volume_desc","id_asc","id_desc"] as [string, ...string[]]).describe("Sort result by field. Default: market_cap_desc").optional(),
      "per_page": z.number().describe("Total results per page. Default: 100 Valid values: 1...250").optional(),
      "page": z.number().describe("Page through results. Default: 1").optional(),
      "sparkline": z.boolean().describe("Include sparkline 7-day data. Default: false").optional(),
      "price_change_percentage": z.string().describe("Include price change percentage timeframe, comma-separated if querying more than 1 timeframe. Valid values: 1h, 24h, 7d, 14d, 30d, 200d, 1y").optional(),
      "locale": z.enum(["ar","bg","cs","da","de","el","en","es","fi","fr","he","hi","hr","hu","id","it","ja","ko","lt","nl","no","pl","pt","ro","ru","sk","sl","sv","th","tr","uk","vi","zh","zh-tw"] as [string, ...string[]]).describe("Language background. Default: en").optional(),
      "precision": z.enum(["full","0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18"] as [string, ...string[]]).describe("Decimal places for currency price value").optional(),
      "include_rehypothecated": z.boolean().describe("Include rehypothecated tokens in results. When true, returns market_cap_rank_with_rehypothecated field. Default: false").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/coins/markets";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["vs_currency","ids","names","symbols","include_tokens","category","order","per_page","page","sparkline","price_change_percentage","locale","precision","include_rehypothecated"]);
    const body = omit(args, ["vs_currency","ids","names","symbols","include_tokens","category","order","per_page","page","sparkline","price_change_percentage","locale","precision","include_rehypothecated","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

server.tool(
  "coin_price_by_ids_symbols_or_names",
  "To query the prices of one or more coins by using their unique Coin API IDs, symbols, or names",
  {
      "vs_currencies": z.string().describe("Target currency of coins, comma-separated if querying more than 1 currency. *refers to /simple/supported_vs_currencies"),
      "ids": z.string().describe("Coins' IDs, comma-separated if querying more than 1 coin. *refers to /coins/list").optional(),
      "names": z.string().describe("Coins' names, comma-separated if querying more than 1 coin.").optional(),
      "symbols": z.string().describe("Coins' symbols, comma-separated if querying more than 1 coin.").optional(),
      "include_tokens": z.enum(["top","all"] as [string, ...string[]]).describe("For symbols lookups, specify all to include all matching tokens. Default top returns top-ranked tokens by market cap or volume.").optional(),
      "include_market_cap": z.boolean().describe("Include market capitalization. Default: false").optional(),
      "include_24hr_vol": z.boolean().describe("Include 24-hour trading volume. Default: false").optional(),
      "include_24hr_change": z.boolean().describe("Include 24-hour change percentage. Default: false").optional(),
      "include_last_updated_at": z.boolean().describe("Include last updated price time as a UNIX timestamp. Default: false").optional(),
      "precision": z.enum(["full","0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18"] as [string, ...string[]]).describe("Decimal places for currency price value").optional(),
      verbosity: z.enum(["compact", "full"]).optional().describe("Response detail level (default compact)."),
    },
  async (args: any) => {
    let path = "/simple/price";
    for (const k of []) path = path.replace("{" + k + "}", encodeURIComponent(String(args[k])));
    const qs = buildQuery(args, ["vs_currencies","ids","names","symbols","include_tokens","include_market_cap","include_24hr_vol","include_24hr_change","include_last_updated_at","precision"]);
    const body = omit(args, ["vs_currencies","ids","names","symbols","include_tokens","include_market_cap","include_24hr_vol","include_24hr_change","include_last_updated_at","precision","verbosity"]);
    const raw = await call("GET", path + qs);
    return { content: [{ type: "text", text: shapeResponse(raw, { verbosity: (args as any).verbosity, noiseFields: NOISE_FIELDS }) }] };
  }
);

  return server;
}

// Transport: stdio by default (local). MCP_TRANSPORT=http runs Streamable HTTP (hosting).
async function runStdio() {
  await createServer().connect(new StdioServerTransport());
}

async function runHttp(port: number) {
  const { createServer: createHttpServer } = await import("node:http");
  const { StreamableHTTPServerTransport } = await import("@modelcontextprotocol/sdk/server/streamableHttp.js");
  const httpServer = createHttpServer(async (req: any, res: any) => {
    if (!req.url || !req.url.startsWith("/mcp")) { res.writeHead(404).end("not found"); return; }
    if (req.method !== "POST") { res.writeHead(405, { Allow: "POST" }).end("stateless MCP: POST /mcp only"); return; }
    try {
      const body = await readJson(req);
      const handle = async () => {
        const server = createServer();               // fresh per request (stateless)
        const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
        res.on("close", () => { transport.close(); server.close(); });
        await server.connect(transport);
        await transport.handleRequest(req, res, body);
      };
      await handle();
    } catch (e) {
      if (!res.headersSent) res.writeHead(500).end(String(e));
    }
  });
  httpServer.listen(port, () => console.error(`coingecko-api MCP (Streamable HTTP) on :${port}/mcp`));
}

function readJson(req: any): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (c: any) => (data += c));
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : undefined); } catch (e) { reject(e); } });
    req.on("error", reject);
  });
}

// Auto-run only when executed directly. When the gateway imports this module (ANYMCP_EMBEDDED=1)
// it drives the transport itself and injects per-request credentials via credentialContext.
if (!process.env.ANYMCP_EMBEDDED) {
  if (process.env.MCP_TRANSPORT === "http") await runHttp(Number(process.env.PORT) || 3000);
  else await runStdio();
}
